import logging
import os
import smtplib
import time
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.base import MIMEBase
from email import encoders
from datetime import datetime, timezone, timedelta

import httpx
import pywhatkit

from config.settings import settings
from database.db import get_db

logger = logging.getLogger(__name__)

IST = timezone(timedelta(hours=5, minutes=30))


class WhatsAppNotifier:
    """Sends WhatsApp messages via direct WhatsApp (pywhatkit), Cloud API, or email fallback."""

    def __init__(self):
        self.max_retries = settings.MAX_RETRIES
        self.retry_delay = settings.RETRY_DELAY_SECONDS
        self.client = httpx.Client(timeout=30.0)

    # ── WhatsApp Direct (pywhatkit) ──────────────────────────────────────────

    def _send_whatsapp_direct(self, message: str) -> bool:
        """Send via pywhatkit — opens WhatsApp Web and sends to your number.
        Requires WhatsApp Web to be logged in on the machine (chrome/browser).
        """
        phone = settings.WHATSAPP_DIRECT_PHONE
        if not phone:
            logger.warning("WHATSAPP_DIRECT_PHONE not set, skipping direct WhatsApp")
            return False

        try:
            # Send now (wait_time=35 seconds gives WhatsApp Web time to fully load)
            logger.info("Opening WhatsApp Web... please wait 35 seconds for it to load")
            pywhatkit.sendwhatmsg_instantly(
                phone_no=phone,
                message=message,
                wait_time=35,
                tab_close=False,  # Don't auto-close so user can see it was sent
                close_time=0,
            )
            logger.info("WhatsApp direct message sent to %s", phone)
            return True
        except Exception as e:
            logger.error("WhatsApp direct send failed: %s", e)
            return False

    # ── WhatsApp Cloud API (optional, if you have a Meta token) ──────────────

    def _send_cloud_api(self, message: str) -> bool:
        """Send via WhatsApp Cloud API (requires Meta Business token)."""
        if not settings.WHATSAPP_TOKEN or not settings.WHATSAPP_PHONE_NUMBER_ID:
            logger.warning("WhatsApp Cloud API credentials not set, skipping")
            return False

        url = f"{settings.WHATSAPP_API_URL}/{settings.WHATSAPP_PHONE_NUMBER_ID}/messages"
        headers = {
            "Authorization": f"Bearer {settings.WHATSAPP_TOKEN}",
            "Content-Type": "application/json",
        }
        payload = {
            "messaging_product": "whatsapp",
            "to": settings.WHATSAPP_RECIPIENT_WA_ID,
            "type": "text",
            "text": {"body": message},
        }
        try:
            resp = self.client.post(url, json=payload, headers=headers)
            resp.raise_for_status()
            logger.info("WhatsApp Cloud API message sent successfully")
            return True
        except Exception as e:
            logger.error("WhatsApp Cloud API send failed: %s", e)
            return False

    # ── Email Fallback (SMTP) ────────────────────────────────────────────────

    def _send_email(self, message: str, pdf_path: str = None) -> bool:
        """Send via email (SMTP). Used as fallback when WhatsApp fails.
        Can optionally attach a PDF report."""
        if not settings.EMAIL_ENABLED:
            logger.info("Email fallback is disabled")
            return False
        if not settings.EMAIL_SENDER or not settings.EMAIL_PASSWORD or not settings.EMAIL_RECIPIENT:
            logger.warning("Email credentials not fully set, skipping email")
            return False

        date_str = datetime.now(IST).strftime("%d %b %Y")
        subject = f"🚀 AI Updates – {date_str}"

        msg = MIMEMultipart("mixed")
        msg["From"] = settings.EMAIL_SENDER
        msg["To"] = settings.EMAIL_RECIPIENT
        msg["Subject"] = subject

        # Body part
        body_part = MIMEMultipart("alternative")
        
        # HTML body if PDF attached
        if pdf_path:
            html_body = f"""
            <html>
            <body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333;">
                <h2 style="color: #2980b9;">🚀 AI Update Digest – {date_str}</h2>
                <p>Your comprehensive AI intelligence briefing is attached as a PDF.</p>
                <p>The report includes:</p>
                <ul>
                    <li>Tech launches prioritized</li>
                    <li>Categorized by industry (Finance, Medical, Coding, AI Tech, etc.)</li>
                    <li>Impact levels and brief explanations</li>
                    <li>Source links for deeper reading</li>
                </ul>
                <p style="color: #7f8c8d; font-size: 12px;">
                    Generated by AI Agent | Sources: NewsAPI, GitHub, RSS, Tech Blogs
                </p>
            </body>
            </html>
            """
            body_part.attach(MIMEText(html_body, "html"))
            body_part.attach(MIMEText(message, "plain"))
        else:
            body_part.attach(MIMEText(message, "plain"))
        
        msg.attach(body_part)

        # Attach PDF if provided
        if pdf_path and os.path.exists(pdf_path):
            try:
                with open(pdf_path, "rb") as f:
                    pdf_attachment = MIMEBase("application", "octet-stream")
                    pdf_attachment.set_payload(f.read())
                
                encoders.encode_base64(pdf_attachment)
                pdf_filename = os.path.basename(pdf_path)
                pdf_attachment.add_header(
                    "Content-Disposition",
                    f"attachment; filename=\"{pdf_filename}\""
                )
                msg.attach(pdf_attachment)
                logger.info(f"PDF attached: {pdf_filename}")
            except Exception as e:
                logger.error(f"Failed to attach PDF: {e}")

        try:
            if settings.EMAIL_SMTP_PORT == 465:
                server = smtplib.SMTP_SSL(settings.EMAIL_SMTP_HOST, settings.EMAIL_SMTP_PORT)
            else:
                server = smtplib.SMTP(settings.EMAIL_SMTP_HOST, settings.EMAIL_SMTP_PORT)
                server.starttls()

            server.login(settings.EMAIL_SENDER, settings.EMAIL_PASSWORD)
            server.sendmail(settings.EMAIL_SENDER, settings.EMAIL_RECIPIENT, msg.as_string())
            server.quit()
            logger.info("Email sent successfully to %s", settings.EMAIL_RECIPIENT)
            return True
        except Exception as e:
            logger.error("Email send failed: %s", e)
            return False

    # ── Orchestration: try WhatsApp first, then email fallback ───────────────

    def send(self, message: str) -> bool:
        """Try WhatsApp (direct then Cloud API), then fall back to email.
        Each method gets up to max_retries attempts before moving to the next.
        """
        # 1. Try WhatsApp Direct (pywhatkit)
        if settings.WHATSAPP_DIRECT_ENABLED:
            for attempt in range(1, self.max_retries + 1):
                logger.info("WhatsApp Direct attempt %d/%d", attempt, self.max_retries)
                if self._send_whatsapp_direct(message):
                    return True
                if attempt < self.max_retries:
                    time.sleep(self.retry_delay)

        # 2. Try WhatsApp Cloud API (if configured)
        if settings.WHATSAPP_TOKEN:
            for attempt in range(1, self.max_retries + 1):
                logger.info("WhatsApp Cloud API attempt %d/%d", attempt, self.max_retries)
                if self._send_cloud_api(message):
                    return True
                if attempt < self.max_retries:
                    time.sleep(self.retry_delay)

        # 3. Email fallback
        if settings.EMAIL_ENABLED:
            logger.info("WhatsApp failed — falling back to email")
            for attempt in range(1, self.max_retries + 1):
                logger.info("Email attempt %d/%d", attempt, self.max_retries)
                if self._send_email(message):
                    return True
                if attempt < self.max_retries:
                    time.sleep(self.retry_delay)

        logger.error("All notification methods failed after retries")
        return False

    # ── Categorization logic ────────────────────────────────────────────────

    CATEGORIES = {
        "💰 FINANCE & BUSINESS": [
            "finance", "banking", "fintech", "trading", "investment", "stock",
            "economy", "market", "revenue", "profit", "ipo", "acquisition",
            "valuation", "funding", "startup", "enterprise", "business",
            "corporate", "bank", "wall street", "imf", "federal reserve",
            "economist", "financial", "commercial", "industry"
        ],
        "🏥 MEDICAL & HEALTHCARE": [
            "healthcare", "medical", "health", "drug", "diagnosis", "clinical",
            "hospital", "patient", "pharma", "biotech", "biology", "protein",
            "dna", "genome", "therapy", "treatment", "disease", "medicine",
            "doctor", "fda", "trial", "vaccine", "mental health"
        ],
        "💻 CODING & DEVELOPMENT": [
            "coding", "programming", "developer", "devops", "software",
            "github", "code", "debugging", "ide", "api", "sdk", "framework",
            "library", "package", "npm", "pypi", "repository", "commit",
            "pull request", "release", "version"
        ],
        "🤖 AI TECH & MODELS": [
            "gpt", "claude", "gemini", "llama", "mistral", "model", "llm",
            "transformer", "neural", "deep learning", "machine learning",
            "benchmark", "training", "inference", "dataset", "weights",
            "checkpoint", "multimodal", "diffusion", "generative ai"
        ],
        "🔧 INDUSTRIAL & MANUFACTURING": [
            "manufacturing", "factory", "robotics", "automation", "industrial",
            "supply chain", "logistics", "warehouse", "production", "assembly",
            "quality control", "predictive maintenance", "iot", "sensor"
        ],
        "🚗 AUTONOMOUS & VEHICLES": [
            "autonomous", "self-driving", "vehicle", "car", "tesla", "waymo",
            "transportation", "mobility", "drone", "uav", "aviation",
            "shipping", "delivery", "navigation"
        ],
        "🔬 RESEARCH & SCIENCE": [
            "research", "paper", "study", "arxiv", "publication", "academic",
            "university", "lab", "scientific", "discovery", "breakthrough",
            "physics", "chemistry", "mathematics", "quantum"
        ],
        "⚡ HARDWARE & CHIPS": [
            "nvidia", "gpu", "tpu", "chip", "hardware", "cuda", "semiconductor",
            "processor", "cpu", "h100", "h200", "blackwell", "data center",
            "server", "compute", "accelerator"
        ],
        "📱 GENERAL TECH": [
            "tech", "technology", "app", "software", "platform", "digital",
            "internet", "cloud", "aws", "azure", "google cloud", "saas"
        ],
    }

    def _categorize(self, update: dict) -> str:
        """Determine which category an update belongs to."""
        text = f"{update.get('title', '')} {update.get('summary', '')} {update.get('company', '')}".lower()
        
        # Score each category
        scores = {}
        for category, keywords in self.CATEGORIES.items():
            score = sum(1 for kw in keywords if kw in text)
            if score > 0:
                scores[category] = score
        
        if not scores:
            return "📰 OTHER AI NEWS"
        
        # Return category with highest score
        return max(scores, key=scores.get)

    def _format_category(self, category: str, updates: list[dict]) -> str:
        """Format a single category section."""
        lines = [f"\n{category}", "=" * 40]
        
        for i, u in enumerate(updates, 1):
            impact = u.get("impact_level", "medium").upper()
            company = u.get("company", "Unknown")
            title = u.get("title", "No title")[:100]
            summary = u.get("summary", "")[:120]
            url = u.get("source_url", "")
            
            lines.append(f"\n{i}. {title}")
            lines.append(f"   Source: {company}")
            if summary:
                lines.append(f"   {summary}")
            lines.append(f"   Impact: {impact}")
            if url:
                lines.append(f"   Link: {url}")
        
        return "\n".join(lines)

    def format_categorized_messages(self, updates: list[dict]) -> list[str]:
        """Group updates by category and return list of message chunks.
        Each message is kept under 1000 chars to avoid Windows path length issues."""
        date_str = datetime.now(IST).strftime("%d %b %Y")
        
        if not updates:
            return [(
                f"🚀 AI Updates – {date_str}\n\n"
                "No significant AI updates in the last 24h.\n"
                "Stay tuned for tomorrow's briefing."
            )]
        
        # Categorize all updates
        categorized = {}
        for u in updates:
            cat = self._categorize(u)
            if cat not in categorized:
                categorized[cat] = []
            categorized[cat].append(u)
        
        # Sort categories by priority
        priority_order = [
            "💰 FINANCE & BUSINESS",
            "🏥 MEDICAL & HEALTHCARE", 
            "💻 CODING & DEVELOPMENT",
            "🤖 AI TECH & MODELS",
            "🔧 INDUSTRIAL & MANUFACTURING",
            "🚗 AUTONOMOUS & VEHICLES",
            "🔬 RESEARCH & SCIENCE",
            "⚡ HARDWARE & CHIPS",
            "📱 GENERAL TECH",
            "📰 OTHER AI NEWS"
        ]
        
        # Build messages (strict 900 char limit per message for safety)
        MAX_MSG_LEN = 900
        messages = []
        current_msg = f"🚀 AI Updates – {date_str}\n\n📊 Total: {len(updates)} updates\n"
        current_len = len(current_msg)
        
        for cat in priority_order:
            if cat not in categorized:
                continue
            
            cat_updates = categorized[cat]
            cat_header = f"\n{cat}\n" + "=" * 30 + "\n"
            
            # If category has many items, split across multiple messages
            for u in cat_updates:
                impact = u.get("impact_level", "medium").upper()
                company = u.get("company", "Unknown")
                title = u.get("title", "No title")[:80]
                url = u.get("source_url", "")[:60]  # Truncate URL
                
                entry = f"• {title}\n  {company} | {impact}\n"
                if url:
                    entry += f"  {url}\n"
                entry += "\n"
                
                # Check if adding this entry would exceed limit
                if current_len + len(entry) > MAX_MSG_LEN:
                    # Save current message and start new one
                    messages.append(current_msg)
                    current_msg = f"🚀 AI Updates – {date_str} (cont'd)\n{cat_header}{entry}"
                    current_len = len(current_msg)
                else:
                    # Add category header if first item in category
                    if cat_header not in current_msg:
                        current_msg += cat_header
                        current_len += len(cat_header)
                    current_msg += entry
                    current_len += len(entry)
        
        # Add final message
        if current_msg:
            messages.append(current_msg)
        
        return messages

    # ── Digest entry point ───────────────────────────────────────────────────

    def send_digest(self, updates: list[dict]) -> bool:
        """Format and send the daily digest in categorized sections.
        Sends ALL updates, grouped by category, split across multiple messages if needed.
        """
        if not updates:
            logger.warning("No updates to send")
            return True
        
        messages = self.format_categorized_messages(updates)
        logger.info("Sending %d message(s) with %d total updates", len(messages), len(updates))
        
        # Send each message
        all_sent = True
        for i, msg in enumerate(messages, 1):
            logger.info("Sending message %d/%d (%d chars)", i, len(messages), len(msg))
            print(f"\n📤 Sending part {i}/{len(messages)}...")
            
            success = self.send(msg)
            if not success:
                logger.error("Failed to send message %d", i)
                all_sent = False
                break
            
            # Small delay between messages
            if i < len(messages):
                time.sleep(5)
        
        # Mark all as sent if successful
        if all_sent:
            db = get_db()
            update_ids = [u["id"] for u in updates]
            db.mark_digest_sent(update_ids)
            logger.info("Marked %d updates as digest_sent", len(update_ids))
            print(f"\n✅ Sent {len(messages)} message(s) with {len(updates)} updates")
        
        return all_sent

    def send_pdf_digest(self, updates: list[dict]) -> bool:
        """Generate PDF report and send via email.
        Creates a professional PDF with categorized sections, tech launches prioritized.
        """
        if not updates:
            logger.warning("No updates to generate PDF")
            return True
        
        try:
            # Import here to avoid circular imports
            from reporting.pdf_generator import generate_pdf_report
            
            print(f"\n📄 Generating PDF report for {len(updates)} updates...")
            pdf_path = generate_pdf_report(updates)
            
            if not pdf_path or not os.path.exists(pdf_path):
                logger.error("PDF generation failed")
                return False
            
            print(f"✅ PDF generated: {pdf_path}")
            
            # Create summary message for WhatsApp
            date_str = datetime.now(IST).strftime("%d %b %Y")
            summary_msg = (
                f"🚀 AI Updates – {date_str}\n\n"
                f"📄 Your comprehensive AI digest is ready!\n\n"
                f"📊 Total updates: {len(updates)}\n"
                f"📑 Full PDF report sent to your email\n\n"
                f"The report includes:\n"
                f"• Tech launches prioritized\n"
                f"• Industry-wise categorization\n"
                f"• Impact levels & summaries\n"
                f"• Source links for details\n\n"
                f"Check your email ({settings.EMAIL_RECIPIENT}) for the PDF attachment."
            )
            
            # Send WhatsApp notification about PDF
            whatsapp_sent = False
            if settings.WHATSAPP_DIRECT_ENABLED:
                print("📱 Sending WhatsApp notification...")
                whatsapp_sent = self.send(summary_msg)
            
            # Send email with PDF attachment
            email_sent = False
            if settings.EMAIL_ENABLED:
                print("📧 Sending email with PDF attachment...")
                email_body = (
                    f"Your AI Update Digest for {date_str} is attached.\n\n"
                    f"Total updates analyzed: {len(updates)}\n\n"
                    f"The PDF includes categorized sections with tech launches prioritized, "
                    f"impact assessments, and source links for deeper reading."
                )
                email_sent = self._send_email(email_body, pdf_path)
            
            # Mark as sent if either succeeded
            if whatsapp_sent or email_sent:
                db = get_db()
                update_ids = [u["id"] for u in updates]
                db.mark_digest_sent(update_ids)
                logger.info("Marked %d updates as digest_sent", len(update_ids))
                print(f"\n✅ PDF digest delivered! WhatsApp: {whatsapp_sent}, Email: {email_sent}")
                return True
            else:
                logger.error("Both WhatsApp and email failed")
                return False
                
        except Exception as e:
            logger.error(f"PDF digest failed: {e}", exc_info=True)
            return False

    def close(self):
        self.client.close()
